#!/bin/sh

# install yay
cd
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ../
sudo rm -r yay/

# window manager
sudo pacman -S sway polkit
# terminal + program launcher
sudo pacman -S alacritty bemenu

# screenshotting
sudo pacman -S grim slurp
# notifications for volume and screenshots
sudo pacman -S dunst libnotify
# emojis on swaybar
sudo pacman -S ttf-joypixels

# file manager
sudo pacman -S lf 
yay -S ueberzugpp
